language: python

python:
  - "3.5"

install:
  - pip install -r requirements-ci.txt

script:
  - flake8
  - python setup.py develop
  - bash examples/run_all.sh
  - pytest --cov=aiocache tests/
  # - pytest examples/

services:
  - redis-server
  - memcached

after_success:
  - codecov
