language: python

python:
  - "3.5"

install:
  - pip install -r requirements-ci.txt

script:
  - flake8
  - python setup.py develop
  - pytest
  - pytest --cov=aiocache tests/

services:
  - redis-server

after_success:
  - codecov
